### PR TITLE
Sync frontend with backend API parameter changes

### LINKED ISSUE #34: [Bugfix] parameter sync
### Problem

Frontend uses outdated API parameters that no longer match the backend endpoints, causing API calls to fail.

### Expected Behavior

Frontend should use the updated parameters to correctly communicate with the backend API.

### Proposed Fix

_No response_

### Related

_No response_

### PR DESCRIPTION
**Pull request by Yejun620**
## What

Updated API parameters to match backend changes

## Why

Backend API parameters were updated and frontend needed to sync.

## Related Issue

#34

### CODE REVIEW

File: fe/src/App.tsx [hunk 1]
```diff
@@ -1,8 +1,24 @@
...
+        {/* AppLayout이 전체 틀(Navbar 등)을 잡고 있습니다 */}
+        <Route element={<AppLayout />}>
+          {/* 주소창에 / 가 들어오면 Home 컴포넌트를 보여줍니다 */}
+          <Route path="/" element={<Home />} />
+          
+          {/* 주소창에 /players 가 들어오면 Players 컴포넌트를 보여줍니다 */}
+          <Route path="/players" element={<Players />} />
+        </Route>
+      </Routes>
+    </BrowserRouter>
```
Comment (halfmoon01) [inline fe/src/App.tsx]: looks good to me:)
